"""Command-line interface for envguard."""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import List, Optional

from . import __version__
from .checker import ERROR, WARNING, Issue, check
from .parser import ParseError, parse_file
from .schema import build_schema, infer_type
from .secrets import SECRET_KEY_RE, scan

EXIT_OK, EXIT_ISSUES, EXIT_USAGE = 0, 1, 2


class Style:
    def __init__(self, enabled: bool):
        self.enabled = enabled

    def _c(self, code, s):
        return f"\033[{code}m{s}\033[0m" if self.enabled else s

    def red(self, s): return self._c("31", s)
    def yellow(self, s): return self._c("33", s)
    def green(self, s): return self._c("32", s)
    def dim(self, s): return self._c("2", s)
    def bold(self, s): return self._c("1", s)


def _use_color(args) -> bool:
    if getattr(args, "no_color", False) or os.environ.get("NO_COLOR"):
        return False
    return sys.stdout.isatty()


def _report(issues: List[Issue], args, ok_message: str) -> int:
    errors = [i for i in issues if i.level == ERROR]
    warnings = [i for i in issues if i.level == WARNING]
    failed = bool(errors) or (args.fail_on_warning and bool(warnings))

    if args.json:
        print(json.dumps({"ok": not failed, "errors": len(errors), "warnings": len(warnings),
                          "issues": [i.to_dict() for i in issues]}, indent=2))
        return EXIT_ISSUES if failed else EXIT_OK

    st = Style(_use_color(args))
    for i in issues:
        if args.quiet and i.level != ERROR:
            continue
        tag = st.red("error  ") if i.level == ERROR else st.yellow("warning")
        loc = ""
        if i.file:
            loc = st.dim(f"{i.file}:{i.line}  " if i.line else f"{i.file}  ")
        print(f"{tag} {loc}{i.message}")

    if not issues:
        print(st.green("✓ ") + ok_message)
    elif not args.quiet or errors:
        print()
        summary = f"{len(errors)} error(s), {len(warnings)} warning(s)"
        print(st.bold(st.red(summary) if failed else st.yellow(summary)))
    return EXIT_ISSUES if failed else EXIT_OK


def _load(path: str, what: str):
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(f"{what} not found: {path}")
    return parse_file(p)


def cmd_check(args) -> int:
    example = _load(args.example, "example file")
    schema = build_schema(example)
    issues: List[Issue] = []
    for env_path in args.env:
        env = _load(env_path, "env file")
        issues.extend(check(env, schema, strict=args.strict))
    names = ", ".join(args.env)
    return _report(issues, args, f"{names} matches {args.example} ({len(schema.rules)} keys checked)")


def cmd_scan(args) -> int:
    root = Path(args.root)
    paths = [Path(p) for p in args.paths] if args.paths else None
    issues = scan(root, paths, exclude=args.exclude)
    return _report(issues, args, "no committed env files or secrets found")


def _render_example(env, *, keep_values: bool, annotate: bool) -> str:
    out: List[str] = [
        "# Generated by envguard. Commit this file; never commit your real .env.",
        "# Annotate keys with @type, @optional, @choices, @pattern, @min, @max, @secret.",
        "",
    ]
    for key, e in env.entries.items():
        for c in e.comments:
            out.append(f"# {c}" if c else "#")
        secretish = bool(SECRET_KEY_RE.search(key))
        has_annotation = any(c.startswith("@") for c in e.comments)
        if annotate and not has_annotation:
            t = "port" if key.upper().endswith("PORT") and e.value.isdigit() else infer_type(e.value)
            tags = []
            if t != "str":
                tags.append(f"@type {t}")
            if secretish:
                tags.append("@secret")
            if tags:
                out.append("# " + " ".join(tags))
        value = e.value if (keep_values and not secretish) else ""
        if value and any(ch in value for ch in " #\"'\n"):
            value = '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'
        out.append(f"{key}={value}")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def cmd_init(args) -> int:
    env = _load(args.env, "env file")
    target = Path(args.output)
    if target.exists() and not args.force:
        print(f"{target} already exists; use --force to overwrite", file=sys.stderr)
        return EXIT_USAGE
    text = _render_example(env, keep_values=args.keep_values, annotate=not args.no_annotate)
    target.write_text(text, encoding="utf-8")
    print(f"Wrote {target} with {len(env.entries)} key(s)"
          + ("" if args.keep_values else " (values cleared)"))
    return EXIT_OK


def cmd_sync(args) -> int:
    example = _load(args.example, "example file")
    env_path = Path(args.env)
    env = parse_file(env_path) if env_path.exists() else None
    existing = set(env.keys()) if env else set()
    missing = [e for k, e in example.entries.items() if k not in existing]
    if not missing:
        print(f"{env_path} already has every key from {args.example}")
        return EXIT_OK
    lines = [f"{e.key}={'' if SECRET_KEY_RE.search(e.key) else e.value}" for e in missing]
    if args.dry_run:
        print(f"Would add {len(missing)} key(s) to {env_path}:")
        print("\n".join("  " + l for l in lines))
        return EXIT_OK
    prefix = ""
    if env_path.exists():
        current = env_path.read_text(encoding="utf-8")
        prefix = "" if current.endswith("\n") or not current else "\n"
    with env_path.open("a", encoding="utf-8") as f:
        f.write(prefix + f"\n# Added by envguard sync from {args.example}\n" + "\n".join(lines) + "\n")
    print(f"Added {len(missing)} key(s) to {env_path}: {', '.join(e.key for e in missing)}")
    return EXIT_OK


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="envguard",
        description="Keep your .env files honest: validate them against .env.example and keep secrets out of git.",
    )
    p.add_argument("--version", action="version", version=f"envguard {__version__}")
    sub = p.add_subparsers(dest="command", metavar="<command>")

    def output_flags(sp):
        sp.add_argument("--json", action="store_true", help="machine-readable output")
        sp.add_argument("-q", "--quiet", action="store_true", help="only print errors")
        sp.add_argument("--fail-on-warning", action="store_true", help="exit 1 on warnings too")
        sp.add_argument("--no-color", action="store_true", help="disable colored output")

    c = sub.add_parser("check", help="validate .env against .env.example (default)")
    c.add_argument("-e", "--env", action="append", help="env file(s) to check (default: .env)")
    c.add_argument("-x", "--example", default=".env.example", help="example/schema file (default: .env.example)")
    c.add_argument("--strict", action="store_true", help="treat undeclared keys as errors")
    output_flags(c)
    c.set_defaults(func=cmd_check)

    s = sub.add_parser("scan", help="find committed env files and hard-coded secrets")
    s.add_argument("paths", nargs="*", help="files to scan (default: everything git would commit)")
    s.add_argument("--root", default=".", help="project root (default: current directory)")
    s.add_argument("--exclude", action="append", default=[], metavar="GLOB",
                   help="skip paths matching GLOB (repeatable), e.g. 'tests/*'")
    output_flags(s)
    s.set_defaults(func=cmd_scan)

    i = sub.add_parser("init", help="generate .env.example from an existing .env")
    i.add_argument("-e", "--env", default=".env")
    i.add_argument("-o", "--output", default=".env.example")
    i.add_argument("--keep-values", action="store_true", help="keep non-secret values as defaults")
    i.add_argument("--no-annotate", action="store_true", help="don't add inferred @type annotations")
    i.add_argument("-f", "--force", action="store_true", help="overwrite the output file")
    i.set_defaults(func=cmd_init)

    y = sub.add_parser("sync", help="append keys missing from .env (using example defaults)")
    y.add_argument("-e", "--env", default=".env")
    y.add_argument("-x", "--example", default=".env.example")
    y.add_argument("-n", "--dry-run", action="store_true")
    y.set_defaults(func=cmd_sync)
    return p


def main(argv: Optional[List[str]] = None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    if not argv or (argv[0].startswith("-") and argv[0] not in ("-h", "--help", "--version")):
        argv = ["check"] + argv
    args = build_parser().parse_args(argv)
    if getattr(args, "command", None) == "check" and not args.env:
        args.env = [".env"]
    try:
        return args.func(args)
    except FileNotFoundError as exc:
        print(f"envguard: {exc}", file=sys.stderr)
        return EXIT_USAGE
    except ParseError as exc:
        print(f"envguard: {exc}", file=sys.stderr)
        return EXIT_USAGE


if __name__ == "__main__":
    raise SystemExit(main())
